namespace: "angular-poc"

frontend:
  apiUrl: "http://localhost:8080"
  repository:
    image: <+artifact.image>
  replicas: 1
  target:
    port: 80
  service:
    port: 80
  ingress:
    host: "angular.local"
    annotations:
      kubernetes.io/ingress.class: nginx